version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "20:00"
    timezone: Africa/Maputo
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - isneezy
  labels:
  - dependencies
