name: Docker Image

on:
  push:
    branches: [master]
  pull_request:
      branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: docker build --cache-from isneezy/pdf-generator-service -t isneezy/pdf-generator-service .

