name: CI

on:
  push:
    branches: [master]
  pull_request:
      branches: [master]

jobs:
  CI:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: restore cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules
      - name: install
        run: yarn --check-files --frozen-lockfile --non-interactive

      - name: Lint
        run: yarn lint

      - name: audit
        run: yarn audit

      - name: test
      run: yarn test --collectCoverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: build
        run: yarn build
      - name: cache build
        uses: actions/cache@v2
        with:
          path: dist
          key: ${{ runner.os }}-dist

      - name: Release
          if: ${{ contains(github.ref, 'master') || contains(github.ref, 'next') }}
          env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: npx semantic-release

